
package webproject.filmreview.soapresources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapFilmsService", targetNamespace = "http://SoapResources.filmreview.webproject/", wsdlLocation = "http://localhost:8080/filmreview/soapapi?wsdl")
public class SoapFilmsService
    extends Service
{

    private final static URL SOAPFILMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPFILMSSERVICE_EXCEPTION;
    private final static QName SOAPFILMSSERVICE_QNAME = new QName("http://SoapResources.filmreview.webproject/", "SoapFilmsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/filmreview/soapapi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPFILMSSERVICE_WSDL_LOCATION = url;
        SOAPFILMSSERVICE_EXCEPTION = e;
    }

    public SoapFilmsService() {
        super(__getWsdlLocation(), SOAPFILMSSERVICE_QNAME);
    }

    public SoapFilmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPFILMSSERVICE_QNAME, features);
    }

    public SoapFilmsService(URL wsdlLocation) {
        super(wsdlLocation, SOAPFILMSSERVICE_QNAME);
    }

    public SoapFilmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPFILMSSERVICE_QNAME, features);
    }

    public SoapFilmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapFilmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapFilms
     */
    @WebEndpoint(name = "SoapFilmsPort")
    public SoapFilms getSoapFilmsPort() {
        return super.getPort(new QName("http://SoapResources.filmreview.webproject/", "SoapFilmsPort"), SoapFilms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapFilms
     */
    @WebEndpoint(name = "SoapFilmsPort")
    public SoapFilms getSoapFilmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SoapResources.filmreview.webproject/", "SoapFilmsPort"), SoapFilms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPFILMSSERVICE_EXCEPTION!= null) {
            throw SOAPFILMSSERVICE_EXCEPTION;
        }
        return SOAPFILMSSERVICE_WSDL_LOCATION;
    }

}
